### ISSUE TITLE
Context Menu Display

### ISSUE THREAD

**Issue by zeeshanjan82** [ianwalter/ng-context-menu#72]
It would be a good feature to enable the configuration setting related to the display. If the developer would want the menu to appear on right side or left of the target.

**Comment by ianwalter** [comment]
Disagree. Unnecessary complexity.

**Comment by zeeshanjan82** [comment]
I think it will really be required if the target is clicked at a position and the context menu is getting cut by the main window in case the target is to the extreme right side of the page.

**Comment by ianwalter** [comment]
The menu doesn't get cut off for me. Maybe I'm misunderstanding and you could provide a screenshot or jsfiddle.

**Comment by zeeshanjan82** [comment]
Please check the screenshot. I am trying to right click on the div and the context menu is appearing towards the right and is getting cutoff by the window. I am using older version of the library not the latest



![untitled-2](https://cloud.githubusercontent.com/assets/8342604/10596512/a3ff7fc2-7702-11e5-83ed-820f4721279a.png)

**Comment by ianwalter** [comment]
I meant a screenshot of the issue happening on the demo page located at http://ianwalter.github.io/ng-context-menu/#/ -- otherwise, how would I know whether its a legitimate bug of the plugin or a bug of your implementation? -- but in any case, I'm won't be adding new features. I'm looking for a new maintainer for this project.
